# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('banking', models.BooleanField()),
                ('bonus', models.BooleanField()),
                ('status', models.CharField(max_length=6)),
                ('contract_name', models.CharField(max_length=15)),
                ('bike_stands', models.PositiveSmallIntegerField(default=0)),
                ('available_bike_stands', models.PositiveSmallIntegerField(default=0)),
                ('available_bikes', models.PositiveSmallIntegerField(default=0)),
                ('optimal_filling', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField()),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2015, 12, 30, 14, 38, 24, 794164, tzinfo=utc))),
            ],
        ),
    ]
