# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('contract_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('banking', models.BooleanField()),
                ('bonus', models.BooleanField()),
                ('status', models.CharField(max_length=6)),
                ('bike_stands', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
