# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20151213_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='available_bike_stands',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='available_bikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 13, 14, 9, 32, 616387, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='bike_stands',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
