# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160122_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 16, 43, 39, 536498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='station',
            name='optimal_filling',
            field=models.FloatField(),
        ),
    ]
