# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20151213_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AddField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 27, 16, 51, 32, 918477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='last_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
