# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160122_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='optimal_filling',
            new_name='optimal_criterion',
        ),
        migrations.AlterField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 18, 34, 0, 946775, tzinfo=utc)),
        ),
    ]
