# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160122_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationLog',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=6)),
                ('available_bike_stands', models.PositiveSmallIntegerField(default=0)),
                ('available_bikes', models.PositiveSmallIntegerField(default=0)),
                ('optimal_criterion', models.FloatField()),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2016, 1, 22, 20, 1, 31, 380934, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 20, 1, 31, 355294, tzinfo=utc)),
        ),
    ]
