# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160122_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationLog',
        ),
        migrations.AlterField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 20, 37, 30, 901380, tzinfo=utc)),
        ),
    ]
