# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160122_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(max_length=6)),
                ('available_bike_stands', models.PositiveSmallIntegerField(default=0)),
                ('available_bikes', models.PositiveSmallIntegerField(default=0)),
                ('optimal_criterion', models.FloatField()),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 20, 39, 1, 228190, tzinfo=utc)),
        ),
    ]
